---
- name: Ensure certificate directory exists
  file:
    path: '{{ output_dir }}'
    state: directory

- name: Ensure OpenSSH keypair exists
  community.crypto.openssh_keypair:
    path: '{{ output_dir }}/{{ cluster_name }}_ed25519'
    type: ed25519
    comment: '{{ registry_admin.email }}'
  register: keypair

- name: Apply the terraform deployment
  include_tasks: terraform.yml
  vars:
      public_key: '{{ keypair.public_key }}'

- name: Update the inventory
  include_tasks: inventory.yml
