---
- name: Wait for the Compliance Operator to finish installing
  kubernetes.core.k8s_info:
    host: https://api.{{ cluster_name }}.{{ cluster_domain }}:6443
    ca_cert: '{{ cluster_ca_path }}'
    api_key: '{{ openshift_oauth_results.openshift_auth.api_key }}'
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: compliance-operator
    namespace: foo-operator
  register: foo_installed
  until:
  - foo_installed.resources|length > 0
  - (foo_installed.resources|first).status.state == "AtLatestKnown"
  retries: 60
  delay: 10

- name: Leverage the Compliance Operator for a scan
  kubernetes.core.k8s:
    state: present
    host: https://api.{{ cluster_name }}.{{ cluster_domain }}:6443
    ca_cert: '{{ cluster_ca_path }}'
    api_key: '{{ openshift_oauth_results.openshift_auth.api_key }}'
    api_version: compliance.openshift.io/v1alpha1
    kind: ScanSettingBinding
    name: nist-moderate
    namespace: compliance-operator
    definition:
      profiles:
      - apiGroup: compliance.openshift.io/v1alpha1
        kind: Profile
        name: rhcos4-moderate
      settingsRef:
        apiGroup: compliance.openshift.io/v1alpha1
        kind: ScanSetting
        name: default
