---
- name: Pull latest openshift-install release info for version
  uri:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-{{ openshift_version }}/release.txt
    return_content: yes
  register: release_text

- name: Identify minor release version
  set_fact:
    openshift_version_minor: |-
      {{ (release_text.content|regex_search('\nName:\s*4\S*', multiline=true)).split()|last }}

- name: Grab the signing key
  get_url:
    url: https://www.redhat.com/security/fd431d51.txt
    dest: '{{ ansible_env["HOME"] }}/rh_key.txt'

- name: Make the client download directory
  file:
    path: '{{ client_directory }}'
    state: directory

- name: Grab the latest release checksums
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-{{ openshift_version }}/sha256sum.txt
    dest: '{{ client_directory }}/{{ openshift_version_minor }}-sha256sum.txt'

- name: Grab the latest helm checksums
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/sha256sum.txt
    dest: '{{ client_directory }}/helm-sha256sum.txt'

- name: Grab the signature file
  get_url:
    url: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-{{ openshift_version }}/sha256sum.txt.gpg
    dest: '{{ client_directory }}/{{ openshift_version_minor }}-sha256sum.txt.sig'

- name: Import RH key, verify signature
  shell: |
    trust_key() {
        echo -e '5\ny\n' | gpg --command-fd 0 --edit-key security@redhat.com trust
        gpg --update-trustdb
        echo changed
    }
    cd '{{ client_directory }}'
    gpg --list-keys |& grep -qF security@redhat.com || gpg --import ~/rh_key.txt
    gpg --list-keys |& grep -q 'ultimate.*security@redhat\.com' || trust_key
    gpg --verify {{ openshift_version_minor }}-sha256sum.txt.sig |& grep -qF 'Good signature from "Red Hat' || exit 1
  register: import_key
  changed_when: '"changed" in import_key.stdout_lines'

- name: Read installer, client, and helm checksum file data
  slurp:
    src: '{{ client_directory }}/{{ item }}'
  register: checksums
  loop:
  - '{{ openshift_version_minor }}-sha256sum.txt'
  - helm-sha256sum.txt

- name: Read expected sha256 for installer, client, and helm
  set_fact:
    openshift_install_sum: >-
      {{ (checksums.results[0].content | b64decode |
        regex_search('\n?(\S*)\s*openshift-install-linux-' +
          openshift_version_minor|regex_escape() +
          '\.tar\.gz', multiline=true
        )).split() | first
      }}
    openshift_client_sum: >-
      {{ (checksums.results[0].content | b64decode |
        regex_search('\n?(\S*)\s*openshift-client-linux-' +
          openshift_version_minor|regex_escape() +
          '\.tar\.gz', multiline=true
        )).split() | first
      }}
    helm_sum: >-
      {{ (checksums.results[1].content | b64decode |
        regex_search('\n?(\S*)\s*helm-linux-amd64\.tar\.gz', multiline=true
        )).split() | first
      }}

- name: Download latest release
  get_url:
    url: '{{ deconstructed_url }}'
    checksum: sha256:{{ item.sum }}
    dest: '{{ client_directory }}/openshift-{{ item.bin }}.tar.gz'
  vars:
    deconstructed_url: |-
      https://mirror.openshift.com/pub/openshift-v4/clients/{{ item.type }}/
      {%- if item.type == "ocp" -%}
      stable-{{ openshift_version}}
      {%- else -%}
      latest
      {%- endif -%}
      /
      {%- if item.type == "ocp" -%}
      openshift-{{ item.bin }}-linux-{{ openshift_version_minor}}
      {%- else -%}
      {{ item.bin }}-linux-amd64
      {%- endif -%}
      .tar.gz
  register: downloads
  loop:
    - bin: install
      sum: '{{ openshift_install_sum }}'
      type: ocp
    - bin: client
      sum: '{{ openshift_client_sum }}'
      type: ocp
    - bin: helm
      sum: '{{ helm_sum }}'
      type: helm

- name: Remove untarred installers when an update was downloaded
  file:
    path: '{{ client_directory }}/{{ item }}'
    state: absent
  loop:
    - oc
    - openshift-install
    - helm
  when: downloads|json_query("length(results[?changed]) > `0`")

- name: Untar the archives
  unarchive:
    remote_src: yes
    src: '{{ client_directory }}/openshift-{{ item.type }}.tar.gz'
    dest: '{{ client_directory }}/'
    extra_opts:
    - --no-same-owner
    creates: '{{ client_directory }}/{{ item.creates }}'
  loop:
    - type: install
      creates: openshift-install
    - type: client
      creates: oc
    - type: helm
      creates: helm

- name: Compile oc-mirror from source if needed
  include_tasks: compile.yml
  when: lookup("file", bin_recovery_dir + "/oc-mirror", errors="ignore") == ""

- name: Ensure mirror data directory exists
  file:
    path: '{{ mirror_directory }}'
    state: directory

- name: Drop oc-mirror configuration
  template:
    src: imageset-config.yml.j2
    dest: '{{ ansible_env["HOME"] }}/imageset-config.yml'
  register: oc_mirror_config

- name: Ensure pull secret location exists
  file:
    path: '{{ ansible_env["HOME"] }}/.docker'
    state: directory

- name: Drop pull secret for oc-mirror
  copy:
    content: '{{ combined_pull_secret }}'
    dest: '{{ ansible_env["HOME"] }}/.docker/config.json'

# FIXME: Hacky workaround for https://github.com/openshift/oc-mirror/issues/273
- name: Ensure oc-mirror metadata image exists
  shell: |
    podman pull --authfile {{ auth_file }} {{ source_image }} &>/dev/null
    podman push --authfile {{ auth_file }} --remove-signatures {{ source_image }} {{ dest_image }} &>/dev/null
  loop: '{{ range(0,3)|list }}'
  vars:
    source_image: registry.redhat.io/ubi8/ubi:latest
    dest_image: '{{ oc_mirror_metadata_image.split(":", 2)[0] }}:fake'
    auth_file: '{{ ansible_env["HOME"] }}/.docker/config.json'
  when: registry_type == "redhat_quay"
  failed_when: false
  changed_when: false

- name: Mirror content directly into registry
  include_tasks: mirror-directly-to-registry.yml
  when: mirror_directly_to_registry|bool == true

- name: Download mirror content on connected host
  include_tasks: mirror-on-host.yml
  when: mirror_directly_to_registry|bool == false

- name: Identify results directory
  find:
    paths: '{{ mirror_directory }}'
    file_type: directory
    patterns: "results-*"
  register: results

- name: Identify results ICSPs and CatalogSources
  find:
    paths: '{{ (results.files|last).path }}'
    file_type: file
    patterns: '*.yaml'
  when: results.files|length > 0
  register: sources

- name: Recover ICSPs and CatalogSources
  fetch:
    src: '{{ item.path }}'
    dest: '{{ mirror_data_recovery_dir }}/'
    flat: yes
    mode: '0644'
  when: results.files|length > 0
  loop: '{{ sources.files }}'

- name: Prepare recovery directory
  file:
    path: '{{ bin_recovery_dir }}'
    state: directory
  delegate_to: controller

- name: Recover clients
  fetch:
    src: '{{ client_directory }}/{{ item }}'
    dest: '{{ bin_recovery_dir }}/'
    flat: yes
    mode: '0755'
  loop:
  - openshift-install
  - oc
  - helm

- name: Recover oc-mirror
  fetch:
    src: '{{ oc_mirror_binary_location }}'
    dest: '{{ bin_recovery_dir }}/'
    flat: yes
    mode: '0755'
