---
- name: Ensure that the directories exist
  file:
    path: '{{ item }}'
    state: directory
  loop:
  - '{{ ansible_env["HOME"] }}/bin'
  - '{{ mirror_directory }}'

- name: Drop all sneakernet binaries into user's ~/bin
  copy:
    src: '{{ bin_recovery_dir }}/{{ item }}'
    dest: '{{ ansible_env["HOME"] }}/bin/'
    mode: '0755'
  loop:
  - openshift-install
  - oc
  - helm
  - oc-mirror

- name: Drop all oc-mirror data
  copy:
    src: '{{ mirror_data_recovery_dir }}/'
    dest: '{{ mirror_directory }}'

- name: Ensure pull secret location exists
  file:
    path: '{{ ansible_env["HOME"] }}/.docker'
    state: directory

- name: Drop pull secret for oc-mirror
  copy:
    content: '{{ local_registry_pull_secret|from_yaml|to_json }}'
    dest: '{{ ansible_env["HOME"] }}/.docker/config.json'

- name: Identify any disk-based mirror bundles
  find:
    paths: '{{ mirror_directory }}'
    file_type: file
    patterns: 'mirror*.tar'
  when: mirror_directly_to_registry|bool == false
  register: mirrored_content

- name: Publish mirror data into disconnected registry
  command: oc-mirror --from "{{ item.path }}" docker://{{ registry_hostname }}/{{ toplevel_namespace }}
  when: mirror_directly_to_registry|bool == false
  loop: '{{ mirrored_content.files }}'

- name: Identify the latest results
  find:
    paths: '{{ ansible_env["HOME"] }}/oc-mirror-workspace'
    file_type: directory
    patterns: 'results-*'
  register: oc_mirror_results

- name: Identify the CatalogSources and ICSPs from the latest results
  find:
    paths: '{{ (oc_mirror_results.files|last).path }}'
    file_type: file
    patterns: '*.yaml'
  register: oc_mirror_manifests

- name: Copy oc_mirror manifests into place
  copy:
    remote_src: true
    src: '{{ item.path }}'
    dest: '{{ mirror_directory }}/'
  loop: '{{ oc_mirror_manifests.files }}'
