---
- name: Ensure that the directories exist
  file:
    path: '{{ item }}'
    state: directory
  loop:
  - '{{ ansible_env["HOME"] }}/bin'
  - '{{ mirror_directory }}'

- name: Drop all sneakernet binaries into user's ~/bin
  copy:
    src: '{{ bin_recovery_dir }}/{{ item }}'
    dest: '{{ ansible_env["HOME"] }}/bin/'
    mode: '0755'
  loop:
  - openshift-install
  - oc
  - helm
  - oc-mirror

- name: Drop all oc-mirror data
  copy:
    src: '{{ mirror_data_recovery_dir }}/'
    dest: '{{ mirror_directory }}'

- name: Identify andy disk-based mirror bundles
  find:
    paths: '{{ mirror_directory }}'
    file_type: file
    patterns: 'mirror*.tar'
  register: mirrored_content

- name: Publish mirror data into disconnected registry
  command: oc-mirror --from "{{ item.path }}" docker://{{ registry_hostname }}/{{ toplevel_namespace }}
  loop: '{{ mirrored_content.files }}'
