---
foo_catalog: quay.io/redhatgov/oc-mirror-dev:test-catalog-{{ catalog_version }}
foo_catalog_full: true

foo_packages:
- name: foo
  channels:
  - name: beta

foo_expected_versions:
  latest: foo-v0.3.1
  diff: foo-v0.3.2
  prune: foo-v0.1.1
  prune-diff: foo-v0.2.0
