---
output_dir: /output
registry_admin:
  username: admin
  password: '{{ lookup("password", output_dir + "/registry_admin_password") }}'
  email: "admin@{{ cluster_name }}.{{ cluster_domain }}"

cluster_ca_path: '{{ ansible_env["HOME"] }}/cluster-ca.crt'

# environment
cluster_domain: redhat4govaws.io
aws_region: us-east-2

# registry configuration
toplevel_namespace: oc-mirror

# scenario
cluster_name: disco
openshift_version: "4.9"
storage_config_backend: registry
mirror_directly_to_registry: true
registry_type: docker_registry
operators_to_mirror: ["foo"]

# this is automatically tripped on when using the foo operator, but can be manually specified also
conduct_second_publish: false
