---
output_dir: /output
registry_admin:
  username: admin
  password: '{{ lookup("password", output_dir + "/registry_admin_password") }}'
  email: "admin@{{ cluster_name }}.{{ cluster_domain }}"

cluster_ca_path: '{{ ansible_env["HOME"] }}/cluster-ca.crt'

# environment
cluster_domain: redhat4govaws.io
aws_region: us-east-2

# scenario
cluster_name: disco
openshift_version: "4.9"
scenario_stubs:
  metadata_backend: registry
  mirror_method: to_registry
  registry_type: docker_registry
  operators_to_mirror: compliance_operator
