- name: Ensure proxy CA certificate is present in anchors
  become: true
  copy:
    src: '{{ output_dir }}/squid.crt'
    dest: /etc/pki/ca-trust/source/anchors/
  register: squid_ca

- name: Ensure registry certificate is present in anchors
  become: true
  copy:
    content: '{{ hostvars.registry.selfsigned_certificate.certificate }}'
    dest: /etc/pki/ca-trust/source/anchors/registry.crt
  when: hostvars.registry.cert_style|default(None) == "selfsigned"
  register: registry_cert

- name: Ensure any additional CAs are present in anchors
  become: true
  copy:
    content: '{{ item.content }}'
    dest: /etc/pki/ca-trust/source/anchors/{{ item.name }}.crt
  loop: '{{ extra_ca_certificates }}'
  register: extra_cas

- name: Update CA trust
  become: true
  command: update-ca-trust
  when: squid_ca.changed or registry_cert.changed or extra_cas.changed
 
