---
- name: Login to quay registry to validate connection
  containers.podman.podman_login:
    username: '{{ registry_admin.username }}'
    password: '{{ registry_admin.password }}'
    registry: '{{ hostvars.registry.private_hostname }}'
