---
- name: Add the newly provisioned hosts to the inventory
  add_host:
    name: '{{ item.name }}'
    groups: '{{ ["terraformed"] + item.groups|default([]) }}'
    ansible_host: '{{ item.ansible_host }}'
    ansible_user: '{{ item.user }}'
    inventory_dir: '{{ inventory_dir }}'
    tf_private_ip: '{{ item.tf_private_ip }}'
    tf_public_ip: '{{ item.tf_public_ip|default(omit) }}'
    private_hostname: '{{ item.private_hostname }}'
    public_hostname: '{{ item.public_hostname|default(omit) }}'
    ansible_ssh_private_key_file: '{{ keypair.filename }}'
    ansible_ssh_common_args: >-
      {%- if item.jump_host|default(None) != None -%}
        {{ forgettable_host + " " + proxy_command }}
      {%- else -%}
        {{ forgettable_host }}
      {%- endif -%}
  vars:
    proxy_command: >-
      -o 'ProxyCommand=ssh -W %h:%p {{ forgettable_host }} {{ item.jump_host|default(None) }}'
  changed_when: false
  loop:
  - name: registry
    groups:
    - connected
    ansible_host: '{{ terraform.outputs.registry_instance.value.ip }}'
    public_hostname: '{{ terraform.outputs.registry_instance.value.hostname }}'
    private_hostname: '{{ terraform.outputs.registry_instance.value.private_hostname }}'
    user: '{{ terraform.outputs.registry_instance.value.username }}'
    tf_private_ip: '{{ terraform.outputs.registry_instance.value.private_ip }}'
    tf_public_ip: '{{ terraform.outputs.registry_instance.value.ip }}'
  - name: proxy
    groups:
    - connected
    ansible_host: '{{ terraform.outputs.proxy_instance.value.ip }}'
    public_hostname: '{{ terraform.outputs.proxy_instance.value.hostname }}'
    private_hostname: '{{ terraform.outputs.proxy_instance.value.private_hostname }}'
    user: '{{ terraform.outputs.proxy_instance.value.username }}'
    tf_private_ip: '{{ terraform.outputs.proxy_instance.value.private_ip }}'
    tf_public_ip: '{{ terraform.outputs.proxy_instance.value.ip }}'
  - name: bastion
    groups:
    - disconnected
    ansible_host: '{{ terraform.outputs.bastion_instance.value.private_ip }}'
    private_hostname: '{{ terraform.outputs.bastion_instance.value.private_hostname }}'
    user: '{{ terraform.outputs.bastion_instance.value.username }}'
    jump_host: -i "{{ keypair.filename }}" "{{ terraform.outputs.proxy_instance.value.username }}@{{ terraform.outputs.proxy_instance.value.hostname }}"
    tf_private_ip: '{{ terraform.outputs.bastion_instance.value.private_ip }}'
