FROM quay.io/ansible/ansible-runner:stable-2.11-latest

RUN dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
COPY jharmison_redhat-oc_mirror_e2e-latest.tar.gz /extras/
