---
- name: Ensure the bin recovery directory exists
  file:
    path: '{{ bin_recovery_dir }}'
    state: directory
  delegate_to: controller

- name: Check for existing oc-mirror binary
  find:
    paths: '{{ bin_recovery_dir }}'
    file_type: file
    patterns: oc-mirror
  delegate_to: controller
  register: oc_mirror_binary

- name: Compile oc-mirror from source if needed
  include_tasks: compile.yml
  when: oc_mirror_binary.files|length == 0

- name: Bring oc-mirror into connected host
  block:
  - name: Ensure directories exist
    file:
      path: '{{ oc_mirror_binary_location|dirname }}'
      state: directory
  - name: Drop oc-mirror in place
    copy:
      src: '{{ bin_recovery_dir }}/oc-mirror'
      dest: '{{ oc_mirror_binary_location }}'
      mode: '0755'
  when: oc_mirror_binary.files|length > 0

- name: Ensure mirror data directory exists
  file:
    path: '{{ mirror_directory }}'
    state: directory
