---
- block:
  - name: Mirror content to disk
    command: '{{ oc_mirror_binary_location }} --config {{ ansible_env["HOME"] }}/imageset-config.yml {{ mirror_dest }}'
    async: 3600  # wait up to an hour for mirroring
    poll: 5
    args:
      chdir: '{{ remote_mirror_data_dir }}'
    vars:
      mirror_dest: >-
        {% if mirror_directly_to_registry|bool %}
        docker://{{ registry_hostname }}/{{ toplevel_namespace }}
        {% else %}
        file://{{ remote_mirror_data_dir }}
        {% endif %}
    when: oc_mirror_config.changed or force_mirror_update|bool

  - name: Identify results directories
    find:
      paths: '{{ remote_mirror_data_dir }}/oc-mirror-workspace'
      file_type: directory
      patterns: "results-*"
    register: results

  - name: Recover lastest results
    ansible.posix.synchronize:
      src: '{{ (results.files|sort|last).path }}'
      dest: '{{ controller_mirror_data_dir }}/'
      mode: pull
    when: results.files|length > 0

  always: # Recover logs even if anything else fails
  - name: Recover oc-mirror log
    fetch:
      src: '{{ remote_mirror_data_dir }}/.oc-mirror.log'
      dest: '{{ output_dir }}/oc-mirror-{{ ansible_date_time.iso8601_basic_short }}.log'
      flat: yes
      mode: '0644'
