---
- name: Mirror content into registry
  command: '{{ oc_mirror_binary_location }} --config {{ ansible_env["HOME"] }}/imageset-config.yml docker://{{ registry_hostname }}/{{ toplevel_namespace }}'
  async: 3600  # wait up to an hour for mirroring
  poll: 5
  args:
    chdir: '{{ mirror_directory }}'
  when: oc_mirror_config.changed or force_mirror_update|bool
