---
- block:
  - name: Mirror content directly into registry
    include_tasks: mirror-directly-to-registry.yml
    when: mirror_directly_to_registry|bool == true

  - name: Download mirror content on connected host
    include_tasks: mirror-on-host.yml
    when: mirror_directly_to_registry|bool == false

  - name: Identify results directory
    find:
      paths: '{{ mirror_directory }}/oc-mirror-workspace'
      file_type: directory
      patterns: "results-*"
    register: results

  - name: Identify results ICSPs and CatalogSources
    find:
      paths: '{{ (results.files|last).path }}'
      file_type: file
      patterns: '*.yaml'
    when: results.files|length > 0
    register: sources

  - name: Recover ICSPs and CatalogSources
    fetch:
      src: '{{ item.path }}'
      dest: '{{ mirror_data_recovery_dir }}/'
      flat: yes
      mode: '0644'
    when: results.files|length > 0
    loop: '{{ sources.files }}'

  always: # Recover logs even if anything else fails
  - name: Set the timestamp for the log
    set_fact:
      oc_mirror_log_timestamp: '{{ ansible_date_time.iso8601_basic_short  }}'

  - name: Recover oc-mirror log
    fetch:
      src: '{{ mirror_directory }}/.oc-mirror.log'
      dest: '{{ output_dir }}/oc-mirror-{{ oc_mirror_log_timestamp }}.log'
      flat: yes
      mode: '0644'

  - name: Symlink oc-mirror log to latest
    file:
      state: link
      src: '{{ output_dir }}/oc-mirror-{{ oc_mirror_log_timestamp }}.log'
      dest: '{{ output_dir }}/.oc-mirror.log'
      force: yes
    delegate_to: controller
