---
- name: Mirror content to disk
  command: '{{ oc_mirror_binary_location }} --config {{ ansible_env["HOME"] }}/imageset-config.yml file://{{ mirror_directory }}'
  async: 3600  # wait up to an hour for mirroring
  poll: 5
  args:
    chdir: '{{ mirror_directory }}'
  when: oc_mirror_config.changed or force_mirror_update|bool

- name: Identify mirrored content
  find:
    paths: '{{ mirror_directory }}'
    file_type: file
    patterns: 'mirror*.tar'
  register: mirrored_content

- name: Recover mirrored content
  fetch:
    src: '{{ item.path }}'
    dest: '{{ mirror_data_recovery_dir }}/'
    flat: true
    mode: '0644'
  loop: '{{ mirrored_content.files }}'
