---
- block:
  - name: Mirror content to {{ "registry" if mirror_directly_to_registry|bool else "disk" }}
    command: '{{ oc_mirror_binary_location }} --config {{ ansible_env["HOME"] }}/imageset-config.yml {{ mirror_dest }}'
    async: 3600  # wait up to an hour for mirroring
    poll: 5
    args:
      chdir: '{{ remote_mirror_data_dir }}'
    vars:
      mirror_dest: >-
        {% if mirror_directly_to_registry|bool %}
        docker://{{ registry_hostname }}/{{ toplevel_namespace }}
        {% else %}
        file://{{ remote_mirror_data_dir }}
        {% endif %}
    when: oc_mirror_config.changed or force_mirror_update|bool

  - name: Identify results directories
    find:
      paths: '{{ remote_mirror_data_dir }}/oc-mirror-workspace'
      file_type: directory
      patterns: "results-*"
    register: results

  - name: Identify results bundles
    find:
      paths: '{{ remote_mirror_data_dir }}'
      file_type: file
      patterns: "mirror_seq*.tar"
    register: results_bundles

  - name: Recover lastest results directories
    ansible.posix.synchronize:
      src: '{{ results.files|json_query("[].path")|sort|last }}'
      dest: '{{ controller_mirror_data_dir }}/'
      mode: pull
    when: results.files|length > 0

  - name: Recover latest results bundles
    fetch:
      src: '{{ results_bundles.files|json_query("[].path")|sort|last }}'
      dest: '{{ controller_mirror_data_dir }}/'
      flat: yes
      mode: '0644'
    when: results_bundles.files|length > 0

  always: # Recover logs even if anything else fails
  - name: Recover oc-mirror log
    fetch:
      src: '{{ remote_mirror_data_dir }}/{{ item }}'
      dest: '{{ output_dir }}/oc-mirror-{{ ansible_date_time.iso8601_basic_short }}.log'
      flat: yes
      mode: '0644'
    ignore_errors: yes
    loop:
    - .oc-mirror.log
    - .openshift_bundle.log
