---
- name: Check to see if OpenShift is responding
  shell: oc get nodes
  changed_when: false
  failed_when: false
  environment:
    KUBECONFIG: '{{ install_directory }}/auth/kubeconfig'
  register: responding

- name: Check to see if installer Kubeconfig exists
  stat:
    path: '{{ install_directory }}/auth/kubeconfig'
  register: kubeconfig

- name: Check to see if manifests directory exists
  stat:
    path: '{{ install_directory }}/manifests'
  register: manifests
