local_registry_pull_secret: |-
  auths:
    {{ registry_hostname }}:
      auth: {{ (registry_admin.username + ":" + registry_admin.password)|b64encode }}
      email: {{ registry_admin.email }}

# Backend config for registry backend
toplevel_namespace: oc-mirror
oc_mirror_metadata_image: '{{ registry_hostname }}/{{ toplevel_namespace }}/imageset-metadata:latest'
# Backend config for local backend
oc_mirror_metadata_path: '{{ mirror_directory }}'

combined_pull_secret: '{{ console_redhat_com_pull_secret|combine(local_registry_pull_secret|from_yaml, recursive=True)|to_json }}'

storage_config_snippets:
  registry:
    storageConfig:
      registry:
        imageURL: '{{ oc_mirror_metadata_image }}'
  local:
    storageConfig:
      local:
        path: '{{ oc_mirror_metadata_path }}'
