---
- name: Check to see if OpenShift is responding
  shell: '{{ oc_path|default("oc") }} get nodes'
  changed_when: false
  failed_when: false
  environment:
    KUBECONFIG: '{{ install_directory }}/auth/kubeconfig'
  register: responding

- name: Check to see if installer Kubeconfig exists
  stat:
    path: '{{ install_directory }}/auth/kubeconfig'
  register: kubeconfig

- name: Check to see if any tfstate exists
  find:
    paths: '{{ install_directory }}'
    file_type: file
    patterns: '*.tfstate'
  register: tfstate

- name: Check to see if manifests directory exists
  stat:
    path: '{{ install_directory }}/manifests'
  register: manifests
