---
- name: Copy the foo index to the destination before mirroring (this allows us to move it to a different source tag)
  containers.podman.podman_image:
    name: '{{ foo_catalog }}'
    pull: true
    push: true
    auth_file: '{{ ansible_env["HOME"] }}/.docker/config.json'
    push_args:
      dest: '{{ foo_dest_catalog }}'

- name: Merge foo index {{ foo_catalog_version }} into operator catalogs
  catalog_merge:
    operator_catalogs: '{{ operator_catalogs|default([]) }}'
    catalog: '{{ foo_dest_catalog }}'
    full: '{{ foo_catalog_full }}'
    packages: '{{ foo_packages }}'
