---
- name: Merge foo into operator catalogs
  catalog_merge:
    operator_catalogs: '{{ operator_catalogs|default([]) }}'
    catalog: '{{ foo_catalog }}'
    full: '{{ foo_catalog_full }}'
    packages: '{{ foo_packages }}'
