---
# DO NOT USE THIS SCENARIO
#
# IT IS INCOMPLETE PENDING ADDITIONAL FIXES
# https://github.com/openshift/oc-mirror/issues/312
operator_blurb: |
  operators:
    - catalog: quay.io/redhatgov/oc-mirror-dev:test-catalog-latest

operator_install: {}

operator_validate:
  test-catalog-publish:
    installed:
      api_version: packages.operators.coreos.com/v1
      kind: PackageManifest
