---
operator_blurb: |
  operators:
    - catalog: registry.jharmison.com/redhatgov/oc-mirror-dev:test-catalog-latest

operator_install:
  foo-operator:
  - apiVersion: v1
    kind: Namespace
    metadata:
      labels:
        openshift.io/cluster-monitoring: "true"
      name: foo-operator
    spec: {}
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: foo-operator
      namespace: foo-operator
    spec:
      targetNamespaces:
      - foo-operator
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: foo
      namespace: foo-operator
    spec:
      channel: beta
      installPlanApproval: Automatic
      name: foo
      source: oc-mirror-dev-catalog
      sourceNamespace: openshift-marketplace

operator_validate:
  foo-operator:
    installed:
      api_version: operators.coreos.com/v1alpha1
      kind: Subscription
      name: foo
      namespace: foo-operator
      condition: .status.state == "AtLatestKnown"
    works:
      validate:
        api_version: apps/v1
        kind: Deployment
        name: foo-operator
        namespace: foo-operator
        condition: .status.readyReplicas == 1
