---
- name: Provision the infrastructure
  hosts: controller
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  roles:
    # The provisioner role consumes the terraform adjacent to the playbook
    # and exports the created ec2_instances to inventory, while also registering
    # the other outputs from the terraform module for use later in the playbook
  - role: provisioner
  tags:
  - always

- name: Wait for connectivity to all terraformed hosts
  hosts: terraformed
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  gather_facts: false
  roles:
  - role: cloud_init_finished
  tags:
  - always

- name: Update all connected terraformed hosts
  hosts: connected
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  roles:
  - role: updated
  tags:
  - updated

- name: Configure container registry
  hosts: registry
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  vars:
    registry_bucket: '{{ hostvars.controller.terraform.outputs.registry_bucket.value }}'
  roles:
  - role: trusts_proxy
  tasks:
  - include_role:
      name: '{{ registry_type }}'
    vars:
      registry_hostname: '{{ private_hostname }}'
      registry_storage_details:
        host: s3.{{ registry_bucket.region }}.amazonaws.com
        s3_bucket: '{{ registry_bucket.bucket }}'
        s3_access_key: '{{ registry_bucket.access_key }}'
        s3_secret_key: '{{ registry_bucket.secret_key }}'
      password_dir: '{{ output_dir }}/quay_passwords' # only used for Quay
      cert_style: byo
      registry_certificate: '{{ lookup("file", output_dir+"/registry.crt") }}'
      registry_certificate_key: '{{ lookup("file", output_dir+"/registry.key") }}'
  tags:
  - registry

- name: Configure Squid
  hosts: proxy
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  become: true
  vars:
    ca_cert_and_key: '{{ hostvars.controller.ca.stdout }}'
  roles:
  - role: proxy
  tags:
  - proxy

- name: Validate bastion configuration
  hosts: bastion
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  become: true
  roles:
  - role: trusts_proxy
  - role: updated
  - role: validated_bastion
  tags:
  - bastion

- name: Download clients and mirror installation on connected host
  hosts: registry
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  tasks:
  - include_role:
      name: sneakernet
      tasks_from: connected
  tags:
  - sneakernet

- name: Install OpenShift
  hosts: bastion
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  pre_tasks:
  - include_role:
      name: sneakernet
      tasks_from: disconnected
  roles:
  - role: installer
  tags:
  - sneakernet
  - installer
