---
- name: Deprovision the infrastructure
  hosts: controller
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  tasks:

  - name: Uninstall OpenShift
    include_role:
      name: installer
      tasks_from: uninstalled.yml
    vars:
      install_directory: '{{ output_dir }}/install'
      oc_path: '{{ output_dir }}/clients/oc'
      openshift_install_path: '{{ output_dir }}/clients/openshift-install'
      extra_uninstall_env:
        AWS_SHARED_CREDENTIALS_FILE: '{{ output_dir }}/aws_credentials'

  - name: Destroy the terraform deployment
    include_role:
      name: provisioner
      tasks_from: terraform
    vars:
      tf_task_state: absent
      public_key: '{{ lookup("file", output_dir + "/" + cluster_name + "_ed25519.pub", errors="ignore")|default("") }}'
