---
- name: Provision the infrastructure
  hosts: controller
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  pre_tasks:
  - name: Load the scenario content
    include_vars: '{{ playbook_dir }}/vars/scenario_stubs/{{ item.key }}/{{ item.value }}.yml'
    loop: '{{ scenario_stubs|dict2items }}'
  roles:
    # The provisioner role consumes the terraform adjacent to the playbook
    # and exports the created ec2_instances to inventory, while also registering
    # the other outputs from the terraform module for use later in the playbook
  - role: provisioner
  tags:
  - always

- name: Wait for connectivity to all terraformed hosts
  hosts: terraformed
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  gather_facts: false
  roles:
  - role: cloud_init_finished
  post_tasks:
  - name: Load the scenario content for the terraformed nodes
    include_vars: '{{ playbook_dir }}/vars/scenario_stubs/{{ item.key }}/{{ item.value }}.yml'
    loop: '{{ scenario_stubs|dict2items }}'
  tags:
  - always
