---
- name: Import the provisioned infrastructure
  import_playbook: provision.yml

- name: Download clients and mirror installation on connected host
  hosts: registry
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  tasks:
  - include_role:
      name: sneakernet
      tasks_from: connected
  tags:
  - sneakernet

- name: Install OpenShift
  hosts: bastion
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  vars:
    additional_trust_bundle: '{{ lookup("file", output_dir + "/squid.crt") }}'
  pre_tasks:
  - include_role:
      name: sneakernet
      tasks_from: disconnected
  roles:
  - installer
  tags:
  - installer

- name: Install Operators
  hosts: bastion
  vars_files:
  - '{{ playbook_dir }}/vars/defaults.yml'
  module_defaults:
    group/k8s:
      host: https://api.{{ cluster_name }}.{{ cluster_domain }}:6443
      ca_cert: '{{ (lookup("file", output_dir + "/install/auth/kubeconfig)|from_yaml).clusters[0].cluster["certificate-authority-data"]|b64decode }}'
  tasks:
  - block:
    - name: Log in to the cluster
      include_role:
        name: logged_in
    - name: Install and configure operator
      include_role:
        name: operators
    always:
    - name: Log out of the cluster
      include_role:
        name: logged_in
      vars:
        state: absent
  tags:
  - operators
