---
- block:
  - name: Log in to the cluster
    import_role:
      name: logged_in
    vars:
      state: present

  - name: Disable the default OperatorHub sources
    kubernetes.core.k8s:
      state: patched
      host: https://api.{{ cluster_name }}.{{ cluster_domain }}:6443
      ca_cert: '{{ cluster_ca_path }}'
      api_key: '{{ openshift_oauth_results.openshift_auth.api_key }}'
      kind: OperatorHub
      name: cluster
      definition:
        spec:
          disableAllDefaultSources: true

  - name: Restart catalog pod
    kubernetes.core.k8s:
      state: absent
      host: https://api.{{ cluster_name }}.{{ cluster_domain }}:6443
      ca_cert: '{{ cluster_ca_path }}'
      api_key: '{{ openshift_oauth_results.openshift_auth.api_key }}'
      label_selectors:
        - "olm.catalogSource=oc-mirror-dev"
      kind: Pod
      namespace: openshift-marketplace
    when: restart_dev_catalog|default(false)|bool

  - name: Install operator(s)
    include_role:
      name: operator_tests/{{ item }}
      tasks_from: install
    loop: '{{ operators_to_mirror }}'

  - name: Leverage operator(s)
    include_role:
      name: operator_tests/{{ item }}
      tasks_from: operate
    loop: '{{ operators_to_mirror }}'

  - name: Validate operator(s)
    include_role:
      name: operator_tests/{{ item }}
      tasks_from: validate
    loop: '{{ operators_to_mirror }}'

  always:
  - name: Log out of the cluster
    import_role:
      name: logged_in
    vars:
      state: absent
